[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"
]

# Solidity compiler settings
solc_version = "0.8.19"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas settings
gas_limit = 9223372036854775807
gas_price = 20000000000

# Test settings
verbosity = 3
ffi = false
fs_permissions = [{ access = "read-write", path = "./"}]

# Network configurations
[rpc_endpoints]
cronos_testnet = "https://evm-t3.cronos.org"
cronos_mainnet = "https://evm.cronos.org"
localhost = "http://127.0.0.1:8545"

# Etherscan API keys for verification
[etherscan]
cronos_testnet = { key = "${CRONOSCAN_API_KEY}", url = "https://testnet.cronoscan.com/api" }
cronos_mainnet = { key = "${CRONOSCAN_API_KEY}", url = "https://cronoscan.com/api" }

# Deployment profiles
[profile.testnet]
src = "contracts"
out = "out/testnet"
optimizer = true
optimizer_runs = 1000

[profile.mainnet]
src = "contracts"
out = "out/mainnet"
optimizer = true
optimizer_runs = 10000
via_ir = true

# Gas reporter settings
[profile.gas-report]
gas_reports = ["*"]
no_storage_caching = true

# Fuzz testing settings
[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing settings
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# Fmt settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
